#!/bin/sh

case "$1" in
    start)
        /usr/sbin/led_red 
	;;
    stop)
	killall memtester
        ;;
    restart|reload)
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

